### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by djsaikrishna** [TechShreyash/TGDrive#1]
Add video player and thumbnail support
add multi channel support

**Comment by AuraMoon55** [comment]
@djsaikrishna

**Comment by TechShreyash** [comment]
what do you mean by this ? what benefit it would do ?

> thumbnail support
> add multi channel support

explain by giving example.

**Comment by djsaikrishna** [comment]
> what do you mean by this ? what benefit it would do ?
> 
> > thumbnail support
> > add multi channel support
> 
> explain by giving example.

like gdrive index , where we can get direct link and playback support

**Comment by TechShreyash** [comment]
@djsaikrishna playback support will be added soon

but what do you mean by thumbnail support and multi channel support

**Comment by Pe0xonN** [comment]
And also preview images such as jpg, png

**Comment by TechShreyash** [comment]
@Pe0xonN open share link on your browser (or double click file) you can preview it

**Comment by Pe0xonN** [comment]
And it's possible to do that to send a couple of files at once?

**Comment by TechShreyash** [comment]
@Pe0xonN you mean uploading multiple files simultaneously ?

**Comment by Pe0xonN** [comment]
Yes

**Comment by TechShreyash** [comment]
@Pe0xonN you can open mutiple tabs on browser and do that

**Comment by Pe0xonN** [comment]
And there is no other way to do it or it takes some time in the code ?

**Comment by TechShreyash** [comment]
> Is there another way to upload simultaneously?

Currently, this is the only method available for simultaneous uploads.

> It takes some time in the code.

Could you clarify what you mean by this?

**Comment by TechShreyash** [comment]
Video Player Added To TG Drive
