### ISSUE TITLE
Add exiting telegram file upload system

### ISSUE THREAD

**Issue by Gujjugaming2k** [TechShreyash/TGDrive#2]
Hi Team,

Add existing telegram file upload system, no need to re upload just forward file to bot or channel

**Comment by TechShreyash** [comment]
@Gujjugaming2k how the website is supposed to know where to put that file (inside which folder)

**Comment by TechShreyash** [comment]
The requested feature just got released in the latest update

Refer Bot Mode : https://github.com/TechShreyash/TGDrive?tab=readme-ov-file#tg-drives-bot-mode
