### ISSUE TITLE
Add 2 more use full features as mention on desciption

### ISSUE THREAD

**Issue by VFLIXPRIME** [TechShreyash/TGDrive#4]
Hi Admin,

1 - Please add multi url upload (if any challenge then make it upto 10 bulk urls add )
2 - unzip automatically using bot and using url upload (url - www.abc.com/series.zip   for bot - forward zip file it will unzip automatically and upload on set folder) 

Thanks

**Comment by TechShreyash** [comment]
@VFLIXPRIME Probably in future...
