### ISSUE TITLE
Add More Channel

### ISSUE THREAD

**Issue by DevOps523** [TechShreyash/TGDrive#5]
Implement an additional channel for bots to manage high-traffic streaming more effectively.

**Comment by doxadeve** [comment]
Added??

**Comment by TechShreyash** [comment]
@doxadeve Nope

**Comment by TechShreyash** [comment]
@doxadeve i recommend you creating multiple instances of tgdrive with different bots and different channels
and upload your files evenly on each one of them to distribute the load

as i dont plan on updating tgdrive further
