### ISSUE TITLE
is it possible to unarchive (zip/rar) from direct link?

### ISSUE THREAD

**Issue by Gujjugaming2k** [TechShreyash/TGDrive#7]
Hi Team,

is it possible to unarchive (zip/rar) from direct link? 

like url/abc.zip   (lets say that which will content series of 10 episode)
it will extract/unarchive and show all 10 episode or upload that all 10 episode on folder

is it possible ? this will be good feature

**Comment by TechShreyash** [comment]
> is it possible ?

Yes, it is possible. 

However, no new updates will be made to this repository from my side.
